version: '3'
services:

  python_app:
    container_name: 'python_app'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-tier
    ports:
      - 8000:8000

networks:
  app-tier:
    driver: bridge